# Generated by Django 3.2.4 on 2022-11-30 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('caption_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Caption ID')),
                ('caption_NO', models.PositiveSmallIntegerField(verbose_name='第几个描述')),
                ('caption', models.TextField(verbose_name='英文描述')),
                ('zh_machine_translation', models.TextField(verbose_name='机器翻译')),
                ('is_ambiguity', models.BooleanField(default=False, verbose_name='改英文是否歧义')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='图片ID')),
                ('image_name', models.CharField(max_length=34, unique=True, verbose_name='图片名字')),
            ],
        ),
        migrations.CreateModel(
            name='RandomImageID',
            fields=[
                ('Random_imageID_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Random_imageID ID')),
                ('image_id', models.PositiveIntegerField(unique=True, verbose_name='图片id')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
                ('now_index_without_image', models.PositiveIntegerField(default=0, verbose_name='该标注哪个了')),
                ('total_amount_without_image', models.PositiveSmallIntegerField(default=0, verbose_name='计划标注的总量')),
                ('start_index_without_image', models.PositiveIntegerField(default=1, verbose_name='从哪个开始标注')),
                ('now_index_with_image', models.PositiveIntegerField(default=0, verbose_name='该标注哪个了')),
                ('total_amount_with_image', models.PositiveSmallIntegerField(default=0, verbose_name='计划标注的总量')),
                ('start_index_with_image', models.PositiveIntegerField(default=1, verbose_name='从哪个开始标注')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否是管理员')),
            ],
        ),
        migrations.CreateModel(
            name='ZhWithoutImage',
            fields=[
                ('zh_without_image_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ZhWithoutImage ID')),
                ('zh_without_image', models.TextField(verbose_name='不看图片标注的中文')),
                ('caption_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.caption')),
                ('user_that_annots_it', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotation.user')),
            ],
        ),
        migrations.AddField(
            model_name='caption',
            name='image_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.image'),
        ),
        migrations.AddConstraint(
            model_name='caption',
            constraint=models.UniqueConstraint(fields=('image_obj', 'caption_NO'), name='this_caption_of_this_image'),
        ),
    ]
