# Generated by Django 3.2.4 on 2022-11-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='caption_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Caption ID'),
        ),
    ]
