# Generated by Django 3.2.9 on 2022-11-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_alter_caption_caption_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='图片ID'),
        ),
    ]
