# Generated by Django 3.2.9 on 2022-11-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_alter_image_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_amount_with_image',
            field=models.PositiveIntegerField(default=0, verbose_name='计划标注的总量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_amount_without_image',
            field=models.PositiveIntegerField(default=0, verbose_name='计划标注的总量'),
        ),
    ]
